/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Universal Design for Learning (https://sketchfab.com/UDL)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/neural-networks-of-the-brain-fa48173d4532407c9c2a4ba06a9bcd2d
Title: Neural Networks of the Brain
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Brain(props) {
  const { nodes, materials } = useGLTF("/3d/brain.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0.004, 0, 0.004]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      >
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["left_08_-_Default_0_Front_08_-_Default_0"].geometry
            }
            material={materials["08_-_Default"]}
            position={[0, 209.806, 0]}
            scale={0.061}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["right_08_-_Default_0_Front_08_-_Default_0"].geometry
            }
            material={materials["08_-_Default"]}
            position={[0, 209.806, 0]}
            scale={0.061}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["centr_08_-_Default_0_08_-_Default_0"].geometry}
            material={materials["08_-_Default"]}
            position={[0, 209.806, 0]}
            scale={0.061}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["left_08_-_Default_0001_08_-_Default001_0"].geometry
            }
            material={materials["08_-_Default.001"]}
            position={[0, 209.806, 0]}
            scale={0.061}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["right_08_-_Default_0001_08_-_Default001_0"].geometry
            }
            material={materials["08_-_Default.001"]}
            position={[0, 209.806, 0]}
            scale={0.061}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["right_08_-_Default_0_Back_08_-_Default_0"].geometry
            }
            material={materials["08_-_Default"]}
            position={[0, 209.806, 0]}
            scale={0.061}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["left_08_-_Default_0_Back_08_-_Default_0"].geometry}
            material={materials["08_-_Default"]}
            position={[0, 209.806, 0]}
            scale={0.061}
          />
        </group>
      </group>
    </group>
  );
}